apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-serv
  labels:
    app: nginx-web
spec:
  selector:
    matchLabels:
      app: nginx-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: maria-db
        image: mariadb:10.7
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-data
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: ROOT_PASSWORD

          - name: MYSQL_DATABASE
            value: wp_db1

          - name: MYSQL_USER
            value: db_user

          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: USER_PASSWORD

        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
         - containerPort: 3306
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: db-pvc
